version: '3.9'

services:

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - app-network

  redis: 
    image: redis:7
    ports:
    - "6379:6379"



networks:
  app-network:
    driver: bridge